### ISSUE TITLE
When removing field on checkout the terms & conditions is duplicated

### ISSUE THREAD

**Issue by jjui** [flaviocopes/grav-plugin-shoppingcart#32] opened 2016-05-23 12:57 UTC
So tested on blanks slate and Antimatter with all latest betas. 
To replicate: 
In `config/plugins/shoppingcart.yaml` remove eg: 
```
    -
      type: display
      content: PLUGIN_SHOPPINGCART.CHECKOUT_HEADLINE_YOUR_ADDRESS
      markdown: true
```
And voila ^^ Strange.

**Comment by flaviocopes** [comment] 2016-05-30 10:43
On it, looks like a configuration merge issue in Grav

**Comment by flaviocopes** [comment] 2016-06-03 11:28
Confirmed it's a Grav issue. 
If I provide a full form definition in the configuration, you cannot remove from that, just add.

A bit unsure how to proceed here, I don't have an immediate fix for the bug, and until it's solved, I must change how config works.

I will probably provide a very slim checkout form, with just the bare minimum, and provide example form definitions.

**Comment by jjui** [comment] 2016-06-03 12:37
A very slim checkout sounds reasonable, then it would be very handy to have some cheat sheets on the shoppingcart homepage for hints regarding checkout :)
👍

**Comment by flaviocopes** [comment] 2016-07-20 21:22
Also fixed by https://github.com/flaviocopes/grav-plugin-shoppingcart/commit/e8361758aee6cc8352ddcb0c082892bb3f7410ee

**Closed by flaviocopes** 2016-07-20 21:22 UTC

**Comment by jjui** [comment] 2016-07-21 10:35
Great!
